version: "3"
networks: 
  expense:
volumes:
  mysql:
services:
  mysql:
    image: vamsidocker012/mysql:v1 
    container_name: mysql 
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - expense
  backend:
    image: vamsidocker012/backend:v1
    container_name: backend
    command: sh -c "sleep 5 && node /opt/server/index.js"
    depends_on:
      - mysql
    networks:
      - expense
  frontend:
    image: vamsidocker012/frontend:v1
    container_name: frontend
    ports:
      - 80:80
    depends_on:
      - backend 
    networks:
      - expense